services:
  presepy:
    image: andreamarchetti/presepy:latest
    container_name: presepy
    ports:
      - "5000:5000"
    volumes:
      - presepy_data:/usr/src/presepy/instance
    environment:
      - DOCKER_CONTAINER=True

volumes:
  presepy_data: